parser: 'babel-eslint'
parserOptions:
  ecmaVersion: 2021
env:
  node: true
  es6: true
extends:
  - eslint:recommended
  - airbnb-base
rules:
  lines-between-class-members: ["error", "always", { "exceptAfterSingleLine": true }]
  arrow-parens: 0
  arrow-body-style: 0
  block-spacing: ['error', 'never']
  camelcase: 0
  class-methods-use-this: 0
  comma-dangle: 0
  consistent-return: 0
  indent: ['error', 4]
  max-len: 0
  no-param-reassign: 0
  no-prototype-builtins: 0
  no-restricted-syntax: 0
  no-shadow: 0
  no-throw-literal: 0
  no-loop-func: 0
  newline-per-chained-call: 0
  object-curly-spacing: ['error', 'never']
  object-curly-newline: 0
  operator-linebreak: 0
  prefer-destructuring: 0
  prefer-promise-reject-errors: 0
  quotes: ['error', 'single']
